### ISSUE TITLE
Test Microsoft.Framework.TestHost.TestHostTest.ListTest failed on AppVeyor because it fails to initalize DIA DataSource

### ISSUE THREAD

**Issue by troydai** [aspnet/Testing#105]
The test expects 8 lines of output, but it returns 9 when is run on _AppVeyor_. The extra line indicate it fails to initialize the DIA DataSource.

```
   Microsoft.Framework.TestHost.TestHostTest.ListTest [FAIL]
      Output is not 8 lines: [(Log) -> {
        "Name": "Microsoft.Framework.TestHost.TestAdapter.SourceInformationProvider",
        "EventId": 0,
        "Level": "Warning",
        "Message": "Failed to create DIA DataSource. No source information will be available.\r\nSystem.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {E6756135-1E65-4D17-8576-610761398C3C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).\r\n   at Microsoft.Framework.TestHost.TestAdapter.SourceInformationProvider.EnsureInitialized() in C:\\projects\\testing\\src\\Microsoft.Framework.TestHost\\TestAdapter\\SourceInformationProvider.cs:line 155"
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.True_is_true",
        "FullyQualifiedName": "Sample.Tests.SampleTest.True_is_true",
        "Id": "aff12a4f-a508-2f73-ec7f-5fc8db5b9664",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.TheoryTest1(x: 1)",
        "FullyQualifiedName": "Sample.Tests.SampleTest.TheoryTest1(59aa4e764883ee83fff87a6781c1c0b8f53afc9c)",
        "Id": "ca59256b-00d1-5304-567b-d8d451a60193",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.TheoryTest1(x: 2)",
        "FullyQualifiedName": "Sample.Tests.SampleTest.TheoryTest1(0ba594fd0db39798c70de5305d472967a4c7b338)",
        "Id": "017433d5-b59f-5ac5-89a5-b9749609d946",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.TheoryTest1(x: 3)",
        "FullyQualifiedName": "Sample.Tests.SampleTest.TheoryTest1(0ecf2995668df64760d3531efb89bc4b4d34b36e)",
        "Id": "936079c7-26b5-a1f4-ec4a-427c1971cab7",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.TheoryTest2(x: 1, s: \"Hi\")",
        "FullyQualifiedName": "Sample.Tests.SampleTest.TheoryTest2(42c42d4a10ab38fc9de2aea361f4f43dd8e56d59)",
        "Id": "3a95a691-3f50-af4d-e35b-3ce9392fe5a8",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.TheoryTest2(x: 2, s: \"Hi\")",
        "FullyQualifiedName": "Sample.Tests.SampleTest.TheoryTest2(af8bc6dd76b16ffd19a4f2f6046f5ec97723e5da)",
        "Id": "cb2041af-e504-c9bb-bc85-3a46086d0dc4",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.TestFound) -> {
        "CodeFilePath": null,
        "DisplayName": "SampleTest.TheoryTest2(x: 3, s: \"Hi\")",
        "FullyQualifiedName": "Sample.Tests.SampleTest.TheoryTest2(1815f6eb5166a4bee27340d5caf1838077932d3d)",
        "Id": "97d74947-1db7-990e-2d79-b3ceb6934a10",
        "LineNumber": null,
        "Properties": {}
      };(TestDiscovery.Response) -> null]
      Expected: True
      Actual:   False
      Stack Trace:
         TestHostTest.cs(43,0): at Microsoft.Framework.TestHost.TestHostTest.<ListTest>d__2.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    Microsoft.Framework.TestHost.Tests
 
=== TEST EXECUTION SUMMARY ===
   Microsoft.Framework.TestHost.Tests  Total: 6, Errors: 0, Failed: 1, Skip

```

**Comment by troydai** [comment]
@rynowak I need some context of this COM component.

**Comment by rynowak** [comment]
We expect using DIA to fail on systems without VS installed/debugger SDK installed. Tests should exclude log messages from verification.

**Comment by troydai** [comment]
e5238d81b8868698430efd37e357f4c68fa83333
