### ISSUE TITLE
InvalidOperationException while discovering unit tests

### ISSUE THREAD

**Issue by mxpv** [aspnet/Testing#143]
I'm getting an exception while discovering tests.

```
------ Discover test started ------
------ Test started: Project: Core.Tests ------
Starting  Microsoft.Dnx.TestHost [C:\Users\USER\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12364\bin\dnx.exe --appbase "D:\GitHub\lab\test\Core.Tests" Microsoft.Dnx.ApplicationHost --port 60577 Microsoft.Dnx.TestHost --port 59433]
Connected to Microsoft.Dnx.TestHost
Discovering tests in 'D:\GitHub\lab\test\Core.Tests\project.json'
Error discovering tests in 'D:\GitHub\lab\test\Core.Tests\project.json'\r\nSystem.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Method 'Dispose' in type 'Microsoft.Dnx.TestHost.TestHostLoggerProvider' from assembly 'Microsoft.Dnx.TestHost, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: Method 'Dispose' in type 'Microsoft.Dnx.TestHost.TestHostLoggerProvider' from assembly 'Microsoft.Dnx.TestHost, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.<---

========== Discover test finished: 0 found (0:00:00.9931403) ==========
```

`project.json` looks as follows:

```
{
    "version": "1.0.0-*",
    "description": "Core.Tests Class Library",
    "authors": [ "Maksym" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "Core": "1.0.0-*",
        "Microsoft.Framework.Configuration.EnvironmentVariables": "1.0.0-*",
        "Moq": "4.2.1507.118",
        "xunit": "2.1.0-*",
        "xunit.runner.dnx": "2.1.0-*"
    },

    "commands": {
        "test": "xunit.runner.dnx"
    },

    "frameworks": {
        "dnx451": { }
    }
}

```

and `global.json`
```
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta7-12364",
        "runtime": "clr",
        "architecture": "x86"
    }
}
```

Thanks.

**Comment by Eilon** [comment]
This appears to be a dependency issue due to a recent API rename. Please update to the latest and this should be fixed.

Some other helpful info is available here: https://github.com/aspnet/Testing/#troubleshooting
