### ISSUE TITLE
VS 2015 TestExplorer "Unable to read data from the transport connection" when discoverinig Xunit tests

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/Testing#146]
Seeing the following when trying to view my project's tests in VS 2015 Test Explorer.

```
------ Discover test started ------
------ Test started: Project: FOOBAR.Storage.Test ------
Starting  Microsoft.Framework.TestHost [C:\Users\rich\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin\dnx.exe --appbase "D:\Dev\AppDoggie\FOOBAR\test\FOOBAR.Storage.Test" Microsoft.Framework.ApplicationHost --port 65453 Microsoft.Framework.TestHost --port 65478]
Connected to Microsoft.Framework.TestHost
Discovering tests in 'D:\Dev\AppDoggie\FOOBAR\test\FOOBAR.Storage.Test\project.json'
Error discovering tests in 'D:\Dev\AppDoggie\FOOBAR\test\FOOBAR.Storage.Test\project.json'
System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
========== Discover test finished: 0 found (0:00:13.2069858) ==========
```

Tests execute correctly when run from command-line.

Test project is an ASP.NET 5 Beta 6 dnxcore50 library project using Xunit 2.1.0-beta4.

**Comment by Aequoris** [comment]
Does the project.json reference "xunit.runner.visualstudio"?
I was getting that exact same error when that dependency was referenced.

I fixed it by removing it. VS2015 doesn't need it, it works as long as you got "xunit.runner.dnx" as a dependency.

**Comment by bitcrazed** [comment]
@Aequoris Thanks for the tip - yes - looks like that was the cause of the issue - many thanks for the tip!

I sincerely hope that MS invests some effort into making the Test Explorer less fragile and better able to express issues it finds when resolving tests.
